const $=id=>document.getElementById(id);
const video=$('video');
let stream=null,shots=[],blob=null,url='';
const E={};
'statusText statusDot welcomePanel settingsPanel resultPanel helpPanel countdownOverlay countdownNumber flashOverlay thumbs startBtn captureBtn clearBtn fullscreenBtn settingsBtn closeSettingsBtn saveSettingsBtn refreshCamerasBtn switchCameraBtn openHelpBtn closeHelpBtn closeResultBtn restartBtn printBtn shareBtn downloadBtn cameraSelect resolutionSelect photoCountSelect delaySelect layoutSelect mirrorSelect titleInput footerInput filterSelect printGuardSelect resultImage printImage'.split(' ').forEach(id=>E[id]=$(id));
const show=x=>x&&x.classList.add('visible'),hide=x=>x&&x.classList.remove('visible'),wait=ms=>new Promise(r=>setTimeout(r,ms));
function status(t,k=''){E.statusText.textContent=t;E.statusDot.className='dot '+(k==='ok'?'ok':k==='err'?'err':'')}
function apply(){document.body.classList.toggle('mirror-preview',E.mirrorSelect.value!=='none');document.body.classList.toggle('filter-bw',E.filterSelect.value==='bw');document.body.classList.toggle('filter-warm',E.filterSelect.value==='warm');document.body.classList.toggle('filter-cool',E.filterSelect.value==='cool')}
function save(){localStorage.pb=JSON.stringify({r:E.resolutionSelect.value,n:E.photoCountSelect.value,d:E.delaySelect.value,l:E.layoutSelect.value,m:E.mirrorSelect.value,t:E.titleInput.value,f:E.footerInput.value,x:E.filterSelect.value,p:E.printGuardSelect.value});apply()}
function load(){let s={r:'1920x1080',n:'3',d:'5',l:'landscape',m:'preview',t:'Merci pour votre visite',f:'',x:'none',p:'manual'};try{s={...s,...JSON.parse(localStorage.pb||'{}')}}catch{};E.resolutionSelect.value=s.r;E.photoCountSelect.value=s.n;E.delaySelect.value=s.d;E.layoutSelect.value=s.l;E.mirrorSelect.value=s.m;E.titleInput.value=s.t;E.footerInput.value=s.f;E.filterSelect.value=s.x;E.printGuardSelect.value=s.p;apply()}
async function cameras(){let d=await navigator.mediaDevices.enumerateDevices(),c=d.filter(x=>x.kind==='videoinput');E.cameraSelect.innerHTML='';c.forEach((cam,i)=>{let o=document.createElement('option'),n=cam.label||'Caméra '+(i+1);o.value=cam.deviceId;o.textContent=/usb|capture|hdmi|uvc/i.test(n)?'⭐ '+n+' — externe':n;E.cameraSelect.appendChild(o)});return c}
async function start(id=''){try{if(stream)stream.getTracks().forEach(t=>t.stop());let [w,h]=E.resolutionSelect.value.split('x').map(Number),opt={width:{ideal:w},height:{ideal:h},frameRate:{ideal:30,max:30}};if(id)opt.deviceId={exact:id};else opt.facingMode={ideal:'environment'};status('Ouverture caméra…');stream=await navigator.mediaDevices.getUserMedia({video:opt,audio:false});video.srcObject=stream;await video.play();await cameras();hide(E.welcomePanel);E.captureBtn.disabled=E.clearBtn.disabled=false;status('Caméra active','ok')}catch(e){status('Caméra impossible','err');alert('Impossible d’ouvrir la caméra. Vérifie HTTPS, autorisation caméra, carte capture et hub USB-C. '+e.message)}}
function shot(){let c=document.createElement('canvas'),w=video.videoWidth||1920,h=video.videoHeight||1080;c.width=w;c.height=h;let x=c.getContext('2d');if(E.mirrorSelect.value==='output'){x.translate(w,0);x.scale(-1,1)}x.filter=E.filterSelect.value==='bw'?'grayscale(1)':E.filterSelect.value==='warm'?'sepia(.15) saturate(1.1)':E.filterSelect.value==='cool'?'hue-rotate(8deg) saturate(1.05)':'none';x.drawImage(video,0,0,w,h);return c}
function thumbs(){E.thumbs.innerHTML='';shots.forEach(c=>{let i=new Image;i.className='thumb';i.src=c.toDataURL('image/jpeg',.8);E.thumbs.appendChild(i)})}
function round(x,a,b,w,h,r){x.beginPath();x.moveTo(a+r,b);x.arcTo(a+w,b,a+w,b+h,r);x.arcTo(a+w,b+h,a,b+h,r);x.arcTo(a,b+h,a,b,r);x.arcTo(a,b,a+w,b,r);x.closePath()}
function cover(x,img,r){let s=Math.max(r.w/img.width,r.h/img.height),sw=r.w/s,sh=r.h/s;x.save();round(x,r.x,r.y,r.w,r.h,28);x.clip();x.drawImage(img,(img.width-sw)/2,(img.height-sh)/2,sw,sh,r.x,r.y,r.w,r.h);x.restore()}
function slots(n,l,a,g){if(l==='strip2'){let sw=(a.w-g)/2,ch=(a.h-g*(n-1))/n,out=[];for(let s=0;s<2;s++)for(let i=0;i<n;i++)out.push({x:a.x+s*(sw+g),y:a.y+i*(ch+g),w:sw,h:ch});return out}if(n<2)return[a];if(n===2)return l==='portrait'?[{x:a.x,y:a.y,w:a.w,h:(a.h-g)/2},{x:a.x,y:a.y+(a.h+g)/2,w:a.w,h:(a.h-g)/2}]:[{x:a.x,y:a.y,w:(a.w-g)/2,h:a.h},{x:a.x+(a.w+g)/2,y:a.y,w:(a.w-g)/2,h:a.h}];if(n===3)return l==='portrait'?[0,1,2].map(i=>({x:a.x,y:a.y+i*((a.h-g*2)/3+g),w:a.w,h:(a.h-g*2)/3})):[{x:a.x,y:a.y,w:(a.w-g)/2,h:a.h},{x:a.x+(a.w+g)/2,y:a.y,w:(a.w-g)/2,h:(a.h-g)/2},{x:a.x+(a.w+g)/2,y:a.y+(a.h+g)/2,w:(a.w-g)/2,h:(a.h-g)/2}];return[{x:a.x,y:a.y,w:(a.w-g)/2,h:(a.h-g)/2},{x:a.x+(a.w+g)/2,y:a.y,w:(a.w-g)/2,h:(a.h-g)/2},{x:a.x,y:a.y+(a.h+g)/2,w:(a.w-g)/2,h:(a.h-g)/2},{x:a.x+(a.w+g)/2,y:a.y+(a.h+g)/2,w:(a.w-g)/2,h:(a.h-g)/2}]}
async function collage(){let l=E.layoutSelect.value,portrait=l==='portrait',W=portrait?1200:1800,H=portrait?1800:1200,c=document.createElement('canvas');c.width=W;c.height=H;let x=c.getContext('2d'),m=105,g=34;x.fillStyle='#111';x.fillRect(0,0,W,H);x.fillStyle='#fff';round(x,50,50,W-100,H-100,50);x.fill();x.fillStyle='#111';x.textAlign='center';x.font='900 56px -apple-system,BlinkMacSystemFont,Arial';let title=E.titleInput.value.trim(),foot=E.footerInput.value.trim();if(title)x.fillText(title,W/2,m+20,W-m*2);let a={x:m,y:m+(title?100:30),w:W-m*2,h:H-m*2-(title?120:40)-(foot?70:25)},list=l==='strip2'?[...shots,...shots]:shots,slotList=slots(shots.length,l,a,g);list.forEach((im,i)=>cover(x,im,slotList[i]));if(foot){x.font='600 34px -apple-system,BlinkMacSystemFont,Arial';x.fillText(foot,W/2,H-m+25,W-m*2)}return new Promise(r=>c.toBlob(r,'image/png',1))}
async function run(){shots=[];thumbs();E.captureBtn.disabled=true;let n=+E.photoCountSelect.value,d=+E.delaySelect.value;for(let i=0;i<n;i++){status('Photo '+(i+1)+'/'+n);E.countdownOverlay.classList.add('visible');for(let j=d;j>0;j--){E.countdownNumber.textContent=j;await wait(1000)}E.countdownOverlay.classList.remove('visible');E.flashOverlay.classList.add('active');setTimeout(()=>E.flashOverlay.classList.remove('active'),250);shots.push(shot());thumbs();await wait(500)}blob=await collage();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);E.resultImage.src=E.printImage.src=url;show(E.resultPanel);status('Tirage prêt','ok');E.captureBtn.disabled=false;if(E.printGuardSelect.value==='autoPrompt')print()}
function print(){if(blob)window.print()}async function share(){if(blob&&navigator.share){let f=new File([blob],'photobooth.png',{type:'image/png'});try{await navigator.share({files:[f],title:'PhotoBooth'});return}catch{}}if(url)window.open(url)}function dl(){let a=document.createElement('a');a.href=url;a.download='photobooth.png';a.click()}
E.startBtn.onclick=()=>start(E.cameraSelect.value);E.captureBtn.onclick=run;E.clearBtn.onclick=()=>{shots=[];thumbs();hide(E.resultPanel)};E.settingsBtn.onclick=()=>show(E.settingsPanel);E.closeSettingsBtn.onclick=()=>hide(E.settingsPanel);E.saveSettingsBtn.onclick=()=>{save();hide(E.settingsPanel);if(stream)start(E.cameraSelect.value)};E.refreshCamerasBtn.onclick=cameras;E.switchCameraBtn.onclick=()=>show(E.settingsPanel);E.openHelpBtn.onclick=()=>show(E.helpPanel);E.closeHelpBtn.onclick=()=>hide(E.helpPanel);E.closeResultBtn.onclick=()=>hide(E.resultPanel);E.restartBtn.onclick=()=>hide(E.resultPanel);E.printBtn.onclick=print;E.shareBtn.onclick=share;E.downloadBtn.onclick=dl;E.fullscreenBtn.onclick=()=>document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen();E.cameraSelect.onchange=()=>start(E.cameraSelect.value);E.mirrorSelect.onchange=E.filterSelect.onchange=()=>{save();apply()};load();cameras().catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});status('Prêt à démarrer');